# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\OD\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1156, 809)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1121, 741))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 71, 16))
        self.label_6.setObjectName("label_6")
        self.traval_path = QtWidgets.QLineEdit(self.tab)
        self.traval_path.setGeometry(QtCore.QRect(100, 80, 101, 20))
        self.traval_path.setObjectName("traval_path")
        self.weights = QtWidgets.QLineEdit(self.tab)
        self.weights.setGeometry(QtCore.QRect(100, 110, 151, 20))
        self.weights.setObjectName("weights")
        self.hf_combox = QtWidgets.QComboBox(self.tab)
        self.hf_combox.setGeometry(QtCore.QRect(100, 140, 151, 22))
        self.hf_combox.setObjectName("hf_combox")
        self.hf_combox.addItem("")
        self.hf_combox.addItem("")
        self.vf_combox = QtWidgets.QComboBox(self.tab)
        self.vf_combox.setGeometry(QtCore.QRect(100, 170, 151, 22))
        self.vf_combox.setObjectName("vf_combox")
        self.vf_combox.addItem("")
        self.vf_combox.addItem("")
        self.rot_combox = QtWidgets.QComboBox(self.tab)
        self.rot_combox.setGeometry(QtCore.QRect(100, 200, 151, 22))
        self.rot_combox.setObjectName("rot_combox")
        self.rot_combox.addItem("")
        self.rot_combox.addItem("")
        self.base_combox = QtWidgets.QComboBox(self.tab)
        self.base_combox.setGeometry(QtCore.QRect(100, 230, 151, 22))
        self.base_combox.setObjectName("base_combox")
        self.base_combox.addItem("")
        self.base_combox.addItem("")
        self.trainPushButton = QtWidgets.QPushButton(self.tab)
        self.trainPushButton.setGeometry(QtCore.QRect(130, 260, 61, 23))
        self.trainPushButton.setObjectName("trainPushButton")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 30, 211, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutforchart = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutforchart.setContentsMargins(0, 0, 0, 0)
        self.layoutforchart.setObjectName("layoutforchart")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(20, 290, 231, 191))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.trainstopPushButton = QtWidgets.QPushButton(self.tab)
        self.trainstopPushButton.setGeometry(QtCore.QRect(190, 260, 61, 23))
        self.trainstopPushButton.setObjectName("trainstopPushButton")
        self.get_traval_Button = QtWidgets.QPushButton(self.tab)
        self.get_traval_Button.setGeometry(QtCore.QRect(210, 80, 41, 23))
        self.get_traval_Button.setObjectName("get_traval_Button")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(510, 20, 20, 461))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.test_begin_Button = QtWidgets.QPushButton(self.tab)
        self.test_begin_Button.setGeometry(QtCore.QRect(1020, 360, 71, 71))
        self.test_begin_Button.setObjectName("test_begin_Button")
        self.img_detect = QtWidgets.QLabel(self.tab)
        self.img_detect.setGeometry(QtCore.QRect(850, 70, 241, 261))
        self.img_detect.setFrameShape(QtWidgets.QFrame.Box)
        self.img_detect.setText("")
        self.img_detect.setObjectName("img_detect")
        self.modelPushButton = QtWidgets.QPushButton(self.tab)
        self.modelPushButton.setGeometry(QtCore.QRect(970, 380, 41, 23))
        self.modelPushButton.setObjectName("modelPushButton")
        self.testpathEdit = QtWidgets.QLineEdit(self.tab)
        self.testpathEdit.setGeometry(QtCore.QRect(650, 350, 311, 20))
        self.testpathEdit.setReadOnly(True)
        self.testpathEdit.setObjectName("testpathEdit")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(550, 50, 61, 16))
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(550, 350, 91, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(550, 380, 91, 16))
        self.label_12.setObjectName("label_12")
        self.test_PushButton = QtWidgets.QPushButton(self.tab)
        self.test_PushButton.setGeometry(QtCore.QRect(970, 350, 41, 23))
        self.test_PushButton.setObjectName("test_PushButton")
        self.img_prim = QtWidgets.QLabel(self.tab)
        self.img_prim.setGeometry(QtCore.QRect(550, 70, 241, 261))
        self.img_prim.setFrameShape(QtWidgets.QFrame.Box)
        self.img_prim.setText("")
        self.img_prim.setObjectName("img_prim")
        self.test_text = QtWidgets.QTextBrowser(self.tab)
        self.test_text.setGeometry(QtCore.QRect(550, 440, 541, 41))
        self.test_text.setObjectName("test_text")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(850, 50, 61, 16))
        self.label_9.setObjectName("label_9")
        self.modelpathEdit = QtWidgets.QLineEdit(self.tab)
        self.modelpathEdit.setGeometry(QtCore.QRect(650, 380, 311, 20))
        self.modelpathEdit.setReadOnly(True)
        self.modelpathEdit.setObjectName("modelpathEdit")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(540, 20, 61, 21))
        self.label_14.setObjectName("label_14")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(0, 500, 1091, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(10, 530, 61, 21))
        self.label_15.setObjectName("label_15")
        self.fastercnn_pingu_button = QtWidgets.QPushButton(self.tab)
        self.fastercnn_pingu_button.setGeometry(QtCore.QRect(70, 530, 61, 23))
        self.fastercnn_pingu_button.setObjectName("fastercnn_pingu_button")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(140, 560, 951, 131))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.fastercnn_chart_pingu = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.fastercnn_chart_pingu.setContentsMargins(0, 0, 0, 0)
        self.fastercnn_chart_pingu.setObjectName("fastercnn_chart_pingu")
        self.frcnn_pinggu_text = QtWidgets.QTextEdit(self.tab)
        self.frcnn_pinggu_text.setGeometry(QtCore.QRect(13, 560, 121, 131))
        self.frcnn_pinggu_text.setObjectName("frcnn_pinggu_text")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(550, 412, 91, 16))
        self.label_35.setObjectName("label_35")
        self.testpathEditout = QtWidgets.QLineEdit(self.tab)
        self.testpathEditout.setGeometry(QtCore.QRect(652, 412, 311, 20))
        self.testpathEditout.setReadOnly(True)
        self.testpathEditout.setObjectName("testpathEditout")
        self.test_PushButton_2 = QtWidgets.QPushButton(self.tab)
        self.test_PushButton_2.setGeometry(QtCore.QRect(970, 412, 41, 23))
        self.test_PushButton_2.setObjectName("test_PushButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.test_begin_Button_1 = QtWidgets.QPushButton(self.tab_2)
        self.test_begin_Button_1.setGeometry(QtCore.QRect(1020, 350, 71, 71))
        self.test_begin_Button_1.setObjectName("test_begin_Button_1")
        self.military_test_model_1 = QtWidgets.QLineEdit(self.tab_2)
        self.military_test_model_1.setGeometry(QtCore.QRect(640, 380, 311, 20))
        self.military_test_model_1.setReadOnly(True)
        self.military_test_model_1.setObjectName("military_test_model_1")
        self.yolomilitary_train_text_1 = QtWidgets.QTextEdit(self.tab_2)
        self.yolomilitary_train_text_1.setGeometry(QtCore.QRect(330, 80, 161, 261))
        self.yolomilitary_train_text_1.setReadOnly(True)
        self.yolomilitary_train_text_1.setObjectName("yolomilitary_train_text_1")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(20, 230, 81, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(20, 110, 91, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(850, 50, 61, 16))
        self.label_18.setObjectName("label_18")
        self.model_PushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.model_PushButton_2.setGeometry(QtCore.QRect(970, 380, 41, 23))
        self.model_PushButton_2.setObjectName("model_PushButton_2")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.label_20.setObjectName("label_20")
        self.yolomilitary_train_button_1 = QtWidgets.QPushButton(self.tab_2)
        self.yolomilitary_train_button_1.setGeometry(QtCore.QRect(180, 320, 61, 23))
        self.yolomilitary_train_button_1.setObjectName("yolomilitary_train_button_1")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(550, 380, 91, 16))
        self.label_21.setObjectName("label_21")
        self.yolomilitary_stop_button_1 = QtWidgets.QPushButton(self.tab_2)
        self.yolomilitary_stop_button_1.setGeometry(QtCore.QRect(250, 320, 61, 23))
        self.yolomilitary_stop_button_1.setObjectName("yolomilitary_stop_button_1")
        self.yolomilitary_pingu_text_1 = QtWidgets.QTextBrowser(self.tab_2)
        self.yolomilitary_pingu_text_1.setGeometry(QtCore.QRect(20, 560, 121, 131))
        self.yolomilitary_pingu_text_1.setObjectName("yolomilitary_pingu_text_1")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 370, 471, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.yolomilitary_chart_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.yolomilitary_chart_1.setContentsMargins(0, 0, 0, 0)
        self.yolomilitary_chart_1.setObjectName("yolomilitary_chart_1")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(10, 530, 61, 21))
        self.label_23.setObjectName("label_23")
        self.img_prim_2 = QtWidgets.QLabel(self.tab_2)
        self.img_prim_2.setGeometry(QtCore.QRect(550, 70, 241, 261))
        self.img_prim_2.setFrameShape(QtWidgets.QFrame.Box)
        self.img_prim_2.setText("")
        self.img_prim_2.setObjectName("img_prim_2")
        self.max_input_size_1 = QtWidgets.QLineEdit(self.tab_2)
        self.max_input_size_1.setGeometry(QtCore.QRect(120, 110, 41, 20))
        self.max_input_size_1.setObjectName("max_input_size_1")
        self.min_input_size_1 = QtWidgets.QLineEdit(self.tab_2)
        self.min_input_size_1.setGeometry(QtCore.QRect(120, 80, 41, 20))
        self.min_input_size_1.setObjectName("min_input_size_1")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(540, 20, 61, 21))
        self.label_24.setObjectName("label_24")
        self.img_detect_2 = QtWidgets.QLabel(self.tab_2)
        self.img_detect_2.setGeometry(QtCore.QRect(850, 70, 241, 261))
        self.img_detect_2.setFrameShape(QtWidgets.QFrame.Box)
        self.img_detect_2.setText("")
        self.img_detect_2.setObjectName("img_detect_2")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(550, 350, 91, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.label_27.setTextFormat(QtCore.Qt.RichText)
        self.label_27.setObjectName("label_27")
        self.military_test_input_1 = QtWidgets.QLineEdit(self.tab_2)
        self.military_test_input_1.setGeometry(QtCore.QRect(642, 350, 311, 20))
        self.military_test_input_1.setReadOnly(True)
        self.military_test_input_1.setObjectName("military_test_input_1")
        self.input_PushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.input_PushButton_2.setGeometry(QtCore.QRect(970, 350, 41, 23))
        self.input_PushButton_2.setObjectName("input_PushButton_2")
        self.test_text_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.test_text_2.setGeometry(QtCore.QRect(550, 438, 541, 51))
        self.test_text_2.setObjectName("test_text_2")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(20, 500, 1071, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(550, 50, 61, 16))
        self.label_29.setObjectName("label_29")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(510, 20, 20, 471))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.labels_text_1 = QtWidgets.QLineEdit(self.tab_2)
        self.labels_text_1.setGeometry(QtCore.QRect(120, 290, 161, 20))
        self.labels_text_1.setObjectName("labels_text_1")
        self.label_46 = QtWidgets.QLabel(self.tab_2)
        self.label_46.setGeometry(QtCore.QRect(20, 286, 91, 20))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_2)
        self.label_47.setGeometry(QtCore.QRect(180, 80, 71, 16))
        self.label_47.setObjectName("label_47")
        self.train_times_1 = QtWidgets.QLineEdit(self.tab_2)
        self.train_times_1.setGeometry(QtCore.QRect(280, 80, 41, 20))
        self.train_times_1.setObjectName("train_times_1")
        self.label_48 = QtWidgets.QLabel(self.tab_2)
        self.label_48.setGeometry(QtCore.QRect(180, 140, 81, 16))
        self.label_48.setObjectName("label_48")
        self.learning_rate_1 = QtWidgets.QLineEdit(self.tab_2)
        self.learning_rate_1.setGeometry(QtCore.QRect(280, 140, 41, 20))
        self.learning_rate_1.setObjectName("learning_rate_1")
        self.label_49 = QtWidgets.QLabel(self.tab_2)
        self.label_49.setGeometry(QtCore.QRect(180, 110, 71, 16))
        self.label_49.setObjectName("label_49")
        self.batch_size_1 = QtWidgets.QLineEdit(self.tab_2)
        self.batch_size_1.setGeometry(QtCore.QRect(280, 110, 41, 20))
        self.batch_size_1.setObjectName("batch_size_1")
        self.nb_epochs_1 = QtWidgets.QLineEdit(self.tab_2)
        self.nb_epochs_1.setGeometry(QtCore.QRect(280, 170, 41, 20))
        self.nb_epochs_1.setObjectName("nb_epochs_1")
        self.label_50 = QtWidgets.QLabel(self.tab_2)
        self.label_50.setGeometry(QtCore.QRect(180, 170, 81, 16))
        self.label_50.setObjectName("label_50")
        self.warmup_epochs_1 = QtWidgets.QLineEdit(self.tab_2)
        self.warmup_epochs_1.setGeometry(QtCore.QRect(120, 170, 41, 20))
        self.warmup_epochs_1.setObjectName("warmup_epochs_1")
        self.label_51 = QtWidgets.QLabel(self.tab_2)
        self.label_51.setGeometry(QtCore.QRect(20, 170, 81, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_2)
        self.label_52.setGeometry(QtCore.QRect(20, 200, 81, 16))
        self.label_52.setObjectName("label_52")
        self.gpus_1 = QtWidgets.QLineEdit(self.tab_2)
        self.gpus_1.setGeometry(QtCore.QRect(120, 140, 41, 20))
        self.gpus_1.setObjectName("gpus_1")
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setGeometry(QtCore.QRect(20, 140, 81, 16))
        self.label_53.setObjectName("label_53")
        self.ignore_thresh_1 = QtWidgets.QLineEdit(self.tab_2)
        self.ignore_thresh_1.setGeometry(QtCore.QRect(120, 200, 41, 20))
        self.ignore_thresh_1.setObjectName("ignore_thresh_1")
        self.image_folder_text_1 = QtWidgets.QLineEdit(self.tab_2)
        self.image_folder_text_1.setGeometry(QtCore.QRect(120, 230, 161, 20))
        self.image_folder_text_1.setObjectName("image_folder_text_1")
        self.image_folder_button_1 = QtWidgets.QPushButton(self.tab_2)
        self.image_folder_button_1.setGeometry(QtCore.QRect(290, 230, 31, 23))
        self.image_folder_button_1.setObjectName("image_folder_button_1")
        self.annot_folder_button_1 = QtWidgets.QPushButton(self.tab_2)
        self.annot_folder_button_1.setGeometry(QtCore.QRect(290, 260, 31, 23))
        self.annot_folder_button_1.setObjectName("annot_folder_button_1")
        self.annot_folder_text_1 = QtWidgets.QLineEdit(self.tab_2)
        self.annot_folder_text_1.setGeometry(QtCore.QRect(120, 260, 161, 20))
        self.annot_folder_text_1.setObjectName("annot_folder_text_1")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(20, 260, 81, 16))
        self.label_19.setObjectName("label_19")
        self.military_test_output_1 = QtWidgets.QLineEdit(self.tab_2)
        self.military_test_output_1.setGeometry(QtCore.QRect(640, 410, 311, 20))
        self.military_test_output_1.setReadOnly(True)
        self.military_test_output_1.setObjectName("military_test_output_1")
        self.output_PushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.output_PushButton_2.setGeometry(QtCore.QRect(970, 410, 41, 23))
        self.output_PushButton_2.setObjectName("output_PushButton_2")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(550, 410, 91, 16))
        self.label_28.setObjectName("label_28")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 530, 941, 161))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.yolomilitary_chart_pingu_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.yolomilitary_chart_pingu_2.setContentsMargins(0, 0, 0, 0)
        self.yolomilitary_chart_pingu_2.setObjectName("yolomilitary_chart_pingu_2")
        self.yolomilitary_pingu_button_1 = QtWidgets.QPushButton(self.tab_2)
        self.yolomilitary_pingu_button_1.setGeometry(QtCore.QRect(70, 530, 61, 23))
        self.yolomilitary_pingu_button_1.setObjectName("yolomilitary_pingu_button_1")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.test_begin_Button_2 = QtWidgets.QPushButton(self.tab_3)
        self.test_begin_Button_2.setGeometry(QtCore.QRect(1020, 350, 71, 71))
        self.test_begin_Button_2.setObjectName("test_begin_Button_2")
        self.city_test_model_2 = QtWidgets.QLineEdit(self.tab_3)
        self.city_test_model_2.setGeometry(QtCore.QRect(640, 378, 321, 20))
        self.city_test_model_2.setReadOnly(True)
        self.city_test_model_2.setObjectName("city_test_model_2")
        self.yolocity_train_text_2 = QtWidgets.QTextEdit(self.tab_3)
        self.yolocity_train_text_2.setGeometry(QtCore.QRect(330, 80, 161, 261))
        self.yolocity_train_text_2.setReadOnly(True)
        self.yolocity_train_text_2.setObjectName("yolocity_train_text_2")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(850, 50, 61, 16))
        self.label_33.setObjectName("label_33")
        self.model_PushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.model_PushButton_3.setGeometry(QtCore.QRect(970, 378, 41, 23))
        self.model_PushButton_3.setObjectName("model_PushButton_3")
        self.yolocity_train_button_2 = QtWidgets.QPushButton(self.tab_3)
        self.yolocity_train_button_2.setGeometry(QtCore.QRect(180, 320, 61, 23))
        self.yolocity_train_button_2.setObjectName("yolocity_train_button_2")
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setGeometry(QtCore.QRect(550, 378, 91, 16))
        self.label_36.setObjectName("label_36")
        self.yolocity_stop_button_2 = QtWidgets.QPushButton(self.tab_3)
        self.yolocity_stop_button_2.setGeometry(QtCore.QRect(250, 320, 61, 23))
        self.yolocity_stop_button_2.setObjectName("yolocity_stop_button_2")
        self.yolocity_pingu_text_2 = QtWidgets.QTextBrowser(self.tab_3)
        self.yolocity_pingu_text_2.setGeometry(QtCore.QRect(20, 560, 121, 131))
        self.yolocity_pingu_text_2.setObjectName("yolocity_pingu_text_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 370, 471, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.yolocity_chart_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.yolocity_chart_2.setContentsMargins(0, 0, 0, 0)
        self.yolocity_chart_2.setObjectName("yolocity_chart_2")
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        self.label_37.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setGeometry(QtCore.QRect(10, 530, 61, 21))
        self.label_38.setObjectName("label_38")
        self.img_prim_3 = QtWidgets.QLabel(self.tab_3)
        self.img_prim_3.setGeometry(QtCore.QRect(550, 70, 241, 261))
        self.img_prim_3.setFrameShape(QtWidgets.QFrame.Box)
        self.img_prim_3.setText("")
        self.img_prim_3.setObjectName("img_prim_3")
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        self.label_39.setGeometry(QtCore.QRect(540, 20, 61, 21))
        self.label_39.setObjectName("label_39")
        self.img_detect_3 = QtWidgets.QLabel(self.tab_3)
        self.img_detect_3.setGeometry(QtCore.QRect(850, 70, 241, 261))
        self.img_detect_3.setFrameShape(QtWidgets.QFrame.Box)
        self.img_detect_3.setText("")
        self.img_detect_3.setObjectName("img_detect_3")
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        self.label_41.setGeometry(QtCore.QRect(550, 348, 91, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.label_42.setTextFormat(QtCore.Qt.RichText)
        self.label_42.setObjectName("label_42")
        self.city_test_input_2 = QtWidgets.QLineEdit(self.tab_3)
        self.city_test_input_2.setGeometry(QtCore.QRect(642, 348, 321, 20))
        self.city_test_input_2.setReadOnly(True)
        self.city_test_input_2.setObjectName("city_test_input_2")
        self.input_PushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.input_PushButton_3.setGeometry(QtCore.QRect(970, 348, 41, 23))
        self.input_PushButton_3.setObjectName("input_PushButton_3")
        self.test_text_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.test_text_3.setGeometry(QtCore.QRect(550, 440, 541, 51))
        self.test_text_3.setObjectName("test_text_3")
        self.line_5 = QtWidgets.QFrame(self.tab_3)
        self.line_5.setGeometry(QtCore.QRect(20, 500, 1071, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(550, 50, 61, 16))
        self.label_44.setObjectName("label_44")
        self.line_6 = QtWidgets.QFrame(self.tab_3)
        self.line_6.setGeometry(QtCore.QRect(510, 20, 20, 471))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_54 = QtWidgets.QLabel(self.tab_3)
        self.label_54.setGeometry(QtCore.QRect(20, 140, 81, 16))
        self.label_54.setObjectName("label_54")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(20, 230, 81, 16))
        self.label_25.setObjectName("label_25")
        self.learning_rate_2 = QtWidgets.QLineEdit(self.tab_3)
        self.learning_rate_2.setGeometry(QtCore.QRect(280, 140, 41, 20))
        self.learning_rate_2.setObjectName("learning_rate_2")
        self.label_55 = QtWidgets.QLabel(self.tab_3)
        self.label_55.setGeometry(QtCore.QRect(180, 140, 81, 16))
        self.label_55.setObjectName("label_55")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(20, 260, 81, 16))
        self.label_30.setObjectName("label_30")
        self.annot_folder_text_2 = QtWidgets.QLineEdit(self.tab_3)
        self.annot_folder_text_2.setGeometry(QtCore.QRect(120, 260, 161, 20))
        self.annot_folder_text_2.setObjectName("annot_folder_text_2")
        self.warmup_epochs_2 = QtWidgets.QLineEdit(self.tab_3)
        self.warmup_epochs_2.setGeometry(QtCore.QRect(120, 170, 41, 20))
        self.warmup_epochs_2.setObjectName("warmup_epochs_2")
        self.image_folder_text_2 = QtWidgets.QLineEdit(self.tab_3)
        self.image_folder_text_2.setGeometry(QtCore.QRect(120, 230, 161, 20))
        self.image_folder_text_2.setObjectName("image_folder_text_2")
        self.labels_text_2 = QtWidgets.QLineEdit(self.tab_3)
        self.labels_text_2.setGeometry(QtCore.QRect(120, 290, 161, 20))
        self.labels_text_2.setObjectName("labels_text_2")
        self.label_56 = QtWidgets.QLabel(self.tab_3)
        self.label_56.setGeometry(QtCore.QRect(20, 286, 91, 20))
        self.label_56.setObjectName("label_56")
        self.min_input_size_2 = QtWidgets.QLineEdit(self.tab_3)
        self.min_input_size_2.setGeometry(QtCore.QRect(120, 80, 41, 20))
        self.min_input_size_2.setObjectName("min_input_size_2")
        self.nb_epochs_2 = QtWidgets.QLineEdit(self.tab_3)
        self.nb_epochs_2.setGeometry(QtCore.QRect(280, 170, 41, 20))
        self.nb_epochs_2.setObjectName("nb_epochs_2")
        self.label_57 = QtWidgets.QLabel(self.tab_3)
        self.label_57.setGeometry(QtCore.QRect(180, 110, 71, 16))
        self.label_57.setObjectName("label_57")
        self.image_folder_button_2 = QtWidgets.QPushButton(self.tab_3)
        self.image_folder_button_2.setGeometry(QtCore.QRect(290, 230, 31, 23))
        self.image_folder_button_2.setObjectName("image_folder_button_2")
        self.label_58 = QtWidgets.QLabel(self.tab_3)
        self.label_58.setGeometry(QtCore.QRect(20, 170, 81, 16))
        self.label_58.setObjectName("label_58")
        self.batch_size_2 = QtWidgets.QLineEdit(self.tab_3)
        self.batch_size_2.setGeometry(QtCore.QRect(280, 110, 41, 20))
        self.batch_size_2.setObjectName("batch_size_2")
        self.train_times_2 = QtWidgets.QLineEdit(self.tab_3)
        self.train_times_2.setGeometry(QtCore.QRect(280, 80, 41, 20))
        self.train_times_2.setObjectName("train_times_2")
        self.label_59 = QtWidgets.QLabel(self.tab_3)
        self.label_59.setGeometry(QtCore.QRect(180, 170, 81, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setGeometry(QtCore.QRect(20, 200, 81, 16))
        self.label_60.setObjectName("label_60")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.label_31.setObjectName("label_31")
        self.gpus_2 = QtWidgets.QLineEdit(self.tab_3)
        self.gpus_2.setGeometry(QtCore.QRect(120, 140, 41, 20))
        self.gpus_2.setObjectName("gpus_2")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setGeometry(QtCore.QRect(180, 80, 71, 16))
        self.label_61.setObjectName("label_61")
        self.annot_folder_button_2 = QtWidgets.QPushButton(self.tab_3)
        self.annot_folder_button_2.setGeometry(QtCore.QRect(290, 260, 31, 23))
        self.annot_folder_button_2.setObjectName("annot_folder_button_2")
        self.ignore_thresh_2 = QtWidgets.QLineEdit(self.tab_3)
        self.ignore_thresh_2.setGeometry(QtCore.QRect(120, 200, 41, 20))
        self.ignore_thresh_2.setObjectName("ignore_thresh_2")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(20, 110, 91, 16))
        self.label_32.setObjectName("label_32")
        self.max_input_size_2 = QtWidgets.QLineEdit(self.tab_3)
        self.max_input_size_2.setGeometry(QtCore.QRect(120, 110, 41, 20))
        self.max_input_size_2.setObjectName("max_input_size_2")
        self.city_test_output_2 = QtWidgets.QLineEdit(self.tab_3)
        self.city_test_output_2.setGeometry(QtCore.QRect(640, 410, 321, 20))
        self.city_test_output_2.setReadOnly(True)
        self.city_test_output_2.setObjectName("city_test_output_2")
        self.output_PushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.output_PushButton_3.setGeometry(QtCore.QRect(970, 410, 41, 23))
        self.output_PushButton_3.setObjectName("output_PushButton_3")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(550, 410, 91, 16))
        self.label_34.setObjectName("label_34")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(150, 530, 941, 161))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.yolocity_chart_pingu_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.yolocity_chart_pingu_2.setContentsMargins(0, 0, 0, 0)
        self.yolocity_chart_pingu_2.setObjectName("yolocity_chart_pingu_2")
        self.yolocity_pingu_button_2 = QtWidgets.QPushButton(self.tab_3)
        self.yolocity_pingu_button_2.setGeometry(QtCore.QRect(70, 530, 61, 23))
        self.yolocity_pingu_button_2.setObjectName("yolocity_pingu_button_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_115 = QtWidgets.QLabel(self.tab_4)
        self.label_115.setGeometry(QtCore.QRect(40, 558, 91, 16))
        self.label_115.setObjectName("label_115")
        self.show_1_outputbutton = QtWidgets.QPushButton(self.tab_4)
        self.show_1_outputbutton.setGeometry(QtCore.QRect(380, 590, 41, 23))
        self.show_1_outputbutton.setObjectName("show_1_outputbutton")
        self.show_1_begin = QtWidgets.QPushButton(self.tab_4)
        self.show_1_begin.setGeometry(QtCore.QRect(430, 530, 71, 71))
        self.show_1_begin.setObjectName("show_1_begin")
        self.show_1_model = QtWidgets.QLineEdit(self.tab_4)
        self.show_1_model.setGeometry(QtCore.QRect(130, 558, 231, 20))
        self.show_1_model.setReadOnly(True)
        self.show_1_model.setObjectName("show_1_model")
        self.label_117 = QtWidgets.QLabel(self.tab_4)
        self.label_117.setGeometry(QtCore.QRect(40, 30, 61, 21))
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QLabel(self.tab_4)
        self.label_118.setGeometry(QtCore.QRect(40, 590, 91, 16))
        self.label_118.setObjectName("label_118")
        self.show_1_input = QtWidgets.QLineEdit(self.tab_4)
        self.show_1_input.setGeometry(QtCore.QRect(132, 528, 231, 20))
        self.show_1_input.setReadOnly(True)
        self.show_1_input.setObjectName("show_1_input")
        self.show_1_pic = QtWidgets.QLabel(self.tab_4)
        self.show_1_pic.setGeometry(QtCore.QRect(40, 60, 461, 421))
        self.show_1_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.show_1_pic.setText("")
        self.show_1_pic.setObjectName("show_1_pic")
        self.show_1_modelbutton = QtWidgets.QPushButton(self.tab_4)
        self.show_1_modelbutton.setGeometry(QtCore.QRect(380, 558, 41, 23))
        self.show_1_modelbutton.setObjectName("show_1_modelbutton")
        self.label_119 = QtWidgets.QLabel(self.tab_4)
        self.label_119.setGeometry(QtCore.QRect(40, 528, 91, 16))
        self.label_119.setObjectName("label_119")
        self.show_1_textedit = QtWidgets.QTextBrowser(self.tab_4)
        self.show_1_textedit.setGeometry(QtCore.QRect(40, 620, 461, 71))
        self.show_1_textedit.setObjectName("show_1_textedit")
        self.show_1_output = QtWidgets.QLineEdit(self.tab_4)
        self.show_1_output.setGeometry(QtCore.QRect(130, 590, 231, 20))
        self.show_1_output.setReadOnly(True)
        self.show_1_output.setObjectName("show_1_output")
        self.show_1_inputbutton = QtWidgets.QPushButton(self.tab_4)
        self.show_1_inputbutton.setGeometry(QtCore.QRect(380, 528, 41, 23))
        self.show_1_inputbutton.setObjectName("show_1_inputbutton")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(40, 490, 461, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_1_button1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.show_1_button1.setObjectName("show_1_button1")
        self.horizontalLayout.addWidget(self.show_1_button1)
        self.show_1_button2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.show_1_button2.setObjectName("show_1_button2")
        self.horizontalLayout.addWidget(self.show_1_button2)
        self.show_1_button3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.show_1_button3.setObjectName("show_1_button3")
        self.horizontalLayout.addWidget(self.show_1_button3)
        self.show_1_button4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.show_1_button4.setObjectName("show_1_button4")
        self.horizontalLayout.addWidget(self.show_1_button4)
        self.line_13 = QtWidgets.QFrame(self.tab_4)
        self.line_13.setGeometry(QtCore.QRect(550, 20, 20, 671))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_120 = QtWidgets.QLabel(self.tab_4)
        self.label_120.setGeometry(QtCore.QRect(610, 30, 61, 21))
        self.label_120.setObjectName("label_120")
        self.show_2_modelbutton = QtWidgets.QPushButton(self.tab_4)
        self.show_2_modelbutton.setGeometry(QtCore.QRect(950, 558, 41, 23))
        self.show_2_modelbutton.setObjectName("show_2_modelbutton")
        self.show_2_pic = QtWidgets.QLabel(self.tab_4)
        self.show_2_pic.setGeometry(QtCore.QRect(610, 60, 461, 421))
        self.show_2_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.show_2_pic.setText("")
        self.show_2_pic.setObjectName("show_2_pic")
        self.show_2_inputbutton = QtWidgets.QPushButton(self.tab_4)
        self.show_2_inputbutton.setGeometry(QtCore.QRect(950, 528, 41, 23))
        self.show_2_inputbutton.setObjectName("show_2_inputbutton")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(610, 490, 461, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.show_2_button1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.show_2_button1.setObjectName("show_2_button1")
        self.horizontalLayout_2.addWidget(self.show_2_button1)
        self.show_2_button2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.show_2_button2.setObjectName("show_2_button2")
        self.horizontalLayout_2.addWidget(self.show_2_button2)
        self.show_2_button3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.show_2_button3.setObjectName("show_2_button3")
        self.horizontalLayout_2.addWidget(self.show_2_button3)
        self.show_2_button4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.show_2_button4.setObjectName("show_2_button4")
        self.horizontalLayout_2.addWidget(self.show_2_button4)
        self.label_121 = QtWidgets.QLabel(self.tab_4)
        self.label_121.setGeometry(QtCore.QRect(610, 528, 91, 16))
        self.label_121.setObjectName("label_121")
        self.show_2_textedit = QtWidgets.QTextBrowser(self.tab_4)
        self.show_2_textedit.setGeometry(QtCore.QRect(610, 620, 461, 71))
        self.show_2_textedit.setObjectName("show_2_textedit")
        self.show_2_output = QtWidgets.QLineEdit(self.tab_4)
        self.show_2_output.setGeometry(QtCore.QRect(700, 590, 231, 20))
        self.show_2_output.setReadOnly(True)
        self.show_2_output.setObjectName("show_2_output")
        self.label_116 = QtWidgets.QLabel(self.tab_4)
        self.label_116.setGeometry(QtCore.QRect(610, 558, 91, 16))
        self.label_116.setObjectName("label_116")
        self.show_2_outputbutton = QtWidgets.QPushButton(self.tab_4)
        self.show_2_outputbutton.setGeometry(QtCore.QRect(950, 590, 41, 23))
        self.show_2_outputbutton.setObjectName("show_2_outputbutton")
        self.show_2_model = QtWidgets.QLineEdit(self.tab_4)
        self.show_2_model.setGeometry(QtCore.QRect(700, 558, 231, 20))
        self.show_2_model.setReadOnly(True)
        self.show_2_model.setObjectName("show_2_model")
        self.show_2_begin = QtWidgets.QPushButton(self.tab_4)
        self.show_2_begin.setGeometry(QtCore.QRect(1000, 530, 71, 71))
        self.show_2_begin.setObjectName("show_2_begin")
        self.show_2_input = QtWidgets.QLineEdit(self.tab_4)
        self.show_2_input.setGeometry(QtCore.QRect(700, 530, 231, 20))
        self.show_2_input.setReadOnly(True)
        self.show_2_input.setObjectName("show_2_input")
        self.label_122 = QtWidgets.QLabel(self.tab_4)
        self.label_122.setGeometry(QtCore.QRect(610, 590, 91, 16))
        self.label_122.setObjectName("label_122")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1156, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pachongButton = QtWidgets.QAction(MainWindow)
        self.pachongButton.setObjectName("pachongButton")
        self.caijianButton = QtWidgets.QAction(MainWindow)
        self.caijianButton.setObjectName("caijianButton")
        self.biaojiButton = QtWidgets.QAction(MainWindow)
        self.biaojiButton.setObjectName("biaojiButton")
        self.menu.addAction(self.pachongButton)
        self.menu.addAction(self.caijianButton)
        self.menu.addAction(self.biaojiButton)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "traval_path"))
        self.label_2.setText(_translate("MainWindow", "num_epochs"))
        self.label_3.setText(_translate("MainWindow", "dataAug_hf"))
        self.label_4.setText(_translate("MainWindow", "dataAug_vf"))
        self.label_5.setText(_translate("MainWindow", "dataAug_rot"))
        self.label_6.setText(_translate("MainWindow", "base_network"))
        self.traval_path.setText(_translate("MainWindow", "G:/tju_object_detection/detect-source/"))
        self.weights.setText(_translate("MainWindow", "100"))
        self.hf_combox.setItemText(0, _translate("MainWindow", "true"))
        self.hf_combox.setItemText(1, _translate("MainWindow", "false"))
        self.vf_combox.setItemText(0, _translate("MainWindow", "true"))
        self.vf_combox.setItemText(1, _translate("MainWindow", "false"))
        self.rot_combox.setItemText(0, _translate("MainWindow", "true"))
        self.rot_combox.setItemText(1, _translate("MainWindow", "false"))
        self.base_combox.setItemText(0, _translate("MainWindow", "resnet50"))
        self.base_combox.setItemText(1, _translate("MainWindow", "vgg"))
        self.trainPushButton.setText(_translate("MainWindow", "开始训练"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">训练参数</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial\'; font-size:13px; color:#333333; background-color:#ffffff;\">Real-time display:</span></p></body></html>"))
        self.trainstopPushButton.setText(_translate("MainWindow", "停止训练"))
        self.get_traval_Button.setText(_translate("MainWindow", "浏览"))
        self.test_begin_Button.setText(_translate("MainWindow", "开始测试"))
        self.modelPushButton.setText(_translate("MainWindow", "浏览"))
        self.testpathEdit.setText(_translate("MainWindow", "../test_big_input/"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">待测图片：</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "待测文件路径："))
        self.label_12.setText(_translate("MainWindow", "模型路径："))
        self.test_PushButton.setText(_translate("MainWindow", "浏览"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">检测结果：</span></p></body></html>"))
        self.modelpathEdit.setText(_translate("MainWindow", "./model_frcnn.hdf5"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">训练</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">测试</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">评估</span></p></body></html>"))
        self.fastercnn_pingu_button.setText(_translate("MainWindow", "开始评估"))
        self.label_35.setText(_translate("MainWindow", "输出文件路径："))
        self.testpathEditout.setText(_translate("MainWindow", "../test_big_output/"))
        self.test_PushButton_2.setText(_translate("MainWindow", "浏览"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "大尺度目标检测"))
        self.test_begin_Button_1.setText(_translate("MainWindow", "开始测试"))
        self.military_test_model_1.setText(_translate("MainWindow", "./YOLO3_75.h5"))
        self.yolomilitary_train_text_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial\'; font-size:13px; color:#333333; background-color:#ffffff;\">Real-time display:</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "image_folder"))
        self.label_17.setText(_translate("MainWindow", "max_input_size"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">检测结果：</span></p></body></html>"))
        self.model_PushButton_2.setText(_translate("MainWindow", "浏览"))
        self.label_20.setText(_translate("MainWindow", "min_input_size"))
        self.yolomilitary_train_button_1.setText(_translate("MainWindow", "开始训练"))
        self.label_21.setText(_translate("MainWindow", "模型文件路径："))
        self.yolomilitary_stop_button_1.setText(_translate("MainWindow", "停止训练"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">训练</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">评估</span></p></body></html>"))
        self.max_input_size_1.setText(_translate("MainWindow", "512"))
        self.min_input_size_1.setText(_translate("MainWindow", "320"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">测试</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "待测文件路径："))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">训练参数</span></p></body></html>"))
        self.military_test_input_1.setText(_translate("MainWindow", "../test_military_input/"))
        self.input_PushButton_2.setText(_translate("MainWindow", "浏览"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">待测图片：</span></p></body></html>"))
        self.labels_text_1.setText(_translate("MainWindow", "\"missile\", \"warship\", \"plane\", \"oiltank\""))
        self.label_46.setText(_translate("MainWindow", "labels"))
        self.label_47.setText(_translate("MainWindow", "train_times"))
        self.train_times_1.setText(_translate("MainWindow", "3"))
        self.label_48.setText(_translate("MainWindow", "learning_rate"))
        self.learning_rate_1.setText(_translate("MainWindow", "1e-4"))
        self.label_49.setText(_translate("MainWindow", "batch_size"))
        self.batch_size_1.setText(_translate("MainWindow", "8"))
        self.nb_epochs_1.setText(_translate("MainWindow", "100"))
        self.label_50.setText(_translate("MainWindow", "nb_epochs"))
        self.warmup_epochs_1.setText(_translate("MainWindow", "3"))
        self.label_51.setText(_translate("MainWindow", "warmup_epochs"))
        self.label_52.setText(_translate("MainWindow", "ignore_thresh"))
        self.gpus_1.setText(_translate("MainWindow", "0"))
        self.label_53.setText(_translate("MainWindow", "gpus"))
        self.ignore_thresh_1.setText(_translate("MainWindow", "0.5"))
        self.image_folder_text_1.setText(_translate("MainWindow", "G:/tju_object_detection/detect-source/val_military/trainingsets/image/"))
        self.image_folder_button_1.setText(_translate("MainWindow", "浏览"))
        self.annot_folder_button_1.setText(_translate("MainWindow", "浏览"))
        self.annot_folder_text_1.setText(_translate("MainWindow", "G:/tju_object_detection/detect-source/val_military/trainingsets/xml/"))
        self.label_19.setText(_translate("MainWindow", "annot_folder"))
        self.military_test_output_1.setText(_translate("MainWindow", "../test_military_output/"))
        self.output_PushButton_2.setText(_translate("MainWindow", "浏览"))
        self.label_28.setText(_translate("MainWindow", "输出文件路径："))
        self.yolomilitary_pingu_button_1.setText(_translate("MainWindow", "开始评估"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "典型军事目标检测"))
        self.test_begin_Button_2.setText(_translate("MainWindow", "开始测试"))
        self.city_test_model_2.setText(_translate("MainWindow", "./YOLO3_75.h5"))
        self.yolocity_train_text_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial\'; font-size:13px; color:#333333; background-color:#ffffff;\">Real-time display:</span></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">检测结果：</span></p></body></html>"))
        self.model_PushButton_3.setText(_translate("MainWindow", "浏览"))
        self.yolocity_train_button_2.setText(_translate("MainWindow", "开始训练"))
        self.label_36.setText(_translate("MainWindow", "模型文件路径"))
        self.yolocity_stop_button_2.setText(_translate("MainWindow", "停止训练"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">训练</span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">评估</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">测试</span></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "待测文件路径："))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">训练参数</span></p></body></html>"))
        self.city_test_input_2.setText(_translate("MainWindow", "../test_city_input/"))
        self.input_PushButton_3.setText(_translate("MainWindow", "浏览"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">待测图片：</span></p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "gpus"))
        self.label_25.setText(_translate("MainWindow", "image_folder"))
        self.learning_rate_2.setText(_translate("MainWindow", "1e-4"))
        self.label_55.setText(_translate("MainWindow", "learning_rate"))
        self.label_30.setText(_translate("MainWindow", "annot_folder"))
        self.annot_folder_text_2.setText(_translate("MainWindow", "G:/tju_object_detection/detect-source/val_city/trainingsets/xml/"))
        self.warmup_epochs_2.setText(_translate("MainWindow", "3"))
        self.image_folder_text_2.setText(_translate("MainWindow", "G:/tju_object_detection/detect-source/val_city/trainingsets/image/"))
        self.labels_text_2.setText(_translate("MainWindow", "\"bridge\", \"oilplatform\", \"train\""))
        self.label_56.setText(_translate("MainWindow", "labels"))
        self.min_input_size_2.setText(_translate("MainWindow", "320"))
        self.nb_epochs_2.setText(_translate("MainWindow", "100"))
        self.label_57.setText(_translate("MainWindow", "batch_size"))
        self.image_folder_button_2.setText(_translate("MainWindow", "浏览"))
        self.label_58.setText(_translate("MainWindow", "warmup_epochs"))
        self.batch_size_2.setText(_translate("MainWindow", "8"))
        self.train_times_2.setText(_translate("MainWindow", "3"))
        self.label_59.setText(_translate("MainWindow", "nb_epochs"))
        self.label_60.setText(_translate("MainWindow", "ignore_thresh"))
        self.label_31.setText(_translate("MainWindow", "min_input_size"))
        self.gpus_2.setText(_translate("MainWindow", "0"))
        self.label_61.setText(_translate("MainWindow", "train_times"))
        self.annot_folder_button_2.setText(_translate("MainWindow", "浏览"))
        self.ignore_thresh_2.setText(_translate("MainWindow", "0.5"))
        self.label_32.setText(_translate("MainWindow", "max_input_size"))
        self.max_input_size_2.setText(_translate("MainWindow", "512"))
        self.city_test_output_2.setText(_translate("MainWindow", "../test_city_output/"))
        self.output_PushButton_3.setText(_translate("MainWindow", "浏览"))
        self.label_34.setText(_translate("MainWindow", "输出文件路径："))
        self.yolocity_pingu_button_2.setText(_translate("MainWindow", "开始评估"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "城市目标检测"))
        self.label_115.setText(_translate("MainWindow", "模型文件路径"))
        self.show_1_outputbutton.setText(_translate("MainWindow", "浏览"))
        self.show_1_begin.setText(_translate("MainWindow", "开始测试"))
        self.show_1_model.setText(_translate("MainWindow", "./model_frcnn.hdf5"))
        self.label_117.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">展示一</span></p></body></html>"))
        self.label_118.setText(_translate("MainWindow", "输出文件路径："))
        self.show_1_input.setText(_translate("MainWindow", "../show1/"))
        self.show_1_modelbutton.setText(_translate("MainWindow", "浏览"))
        self.label_119.setText(_translate("MainWindow", "待测文件路径："))
        self.show_1_output.setText(_translate("MainWindow", "../show1_results/"))
        self.show_1_inputbutton.setText(_translate("MainWindow", "浏览"))
        self.show_1_button1.setText(_translate("MainWindow", "原始图"))
        self.show_1_button2.setText(_translate("MainWindow", "上一张"))
        self.show_1_button3.setText(_translate("MainWindow", "下一张"))
        self.show_1_button4.setText(_translate("MainWindow", "标记图"))
        self.label_120.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">展示二</span></p></body></html>"))
        self.show_2_modelbutton.setText(_translate("MainWindow", "浏览"))
        self.show_2_inputbutton.setText(_translate("MainWindow", "浏览"))
        self.show_2_button1.setText(_translate("MainWindow", "原始图"))
        self.show_2_button2.setText(_translate("MainWindow", "上一张"))
        self.show_2_button3.setText(_translate("MainWindow", "下一张"))
        self.show_2_button4.setText(_translate("MainWindow", "标记图"))
        self.label_121.setText(_translate("MainWindow", "待测文件路径："))
        self.show_2_output.setText(_translate("MainWindow", "../show2_results/"))
        self.label_116.setText(_translate("MainWindow", "模型文件路径"))
        self.show_2_outputbutton.setText(_translate("MainWindow", "浏览"))
        self.show_2_model.setText(_translate("MainWindow", "./YOLO3_75.h5"))
        self.show_2_begin.setText(_translate("MainWindow", "开始测试"))
        self.show_2_input.setText(_translate("MainWindow", "../show2/"))
        self.label_122.setText(_translate("MainWindow", "输出文件路径："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "效果展示"))
        self.menu.setTitle(_translate("MainWindow", "数据采集"))
        self.pachongButton.setText(_translate("MainWindow", "爬虫"))
        self.caijianButton.setText(_translate("MainWindow", "图像裁剪\n"
""))
        self.biaojiButton.setText(_translate("MainWindow", "图像标记"))

